Repository kthss01/KH_FinalTeamProject_Groupware, pull requests merged in 2021-11, with the labels that each got.

#122 커뮤니티 1차 테스트 진행중
  GroupwarePro/src/main/java/com/kh/spring/community/controller/CommunityController.java
  GroupwarePro/src/main/java/com/kh/spring/community/model/dao/CommunityDao.java
  GroupwarePro/src/main/java/com/kh/spring/community/model/service/CommunityService.java
  GroupwarePro/src/main/java/com/kh/spring/community/model/service/CommunityServiceImpl.java
  GroupwarePro/src/main/resources/mappers/community-mapper.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/community/communityBoardDetailView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/community/enrollBoardForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/manager/managerCommProposal.jsp
  GroupwarePro/src/main/webapp/resources/upload_files/2021111718012648192.jpg
  GroupwarePro/src/main/webapp/resources/upload_files/2021111718063147252.jpg
  GroupwarePro/src/main/webapp/resources/upload_files/2021111718063189902.png
  GroupwarePro/src/main/webapp/resources/upload_files/2021111718091658853.jpg
  GroupwarePro/src/main/webapp/resources/upload_files/2021111719302685991.jpg
  GroupwarePro/src/main/webapp/resources/upload_files/2021111719383489794.png
Labels: 테스트 구현

#161 전자결재 기안, 결재기능 구현완료
  GroupwarePro/src/main/java/com/kh/spring/EApproval/model/vo/EForm.java
  GroupwarePro/src/main/java/com/kh/spring/eApproval/controller/EApprovalController.java
  GroupwarePro/src/main/java/com/kh/spring/eApproval/model/dao/EApprovalDao.java
  GroupwarePro/src/main/java/com/kh/spring/eApproval/model/service/EApprovalService.java
  GroupwarePro/src/main/java/com/kh/spring/eApproval/model/service/EApprovalServiceImpl.java
  GroupwarePro/src/main/java/com/kh/spring/eApproval/model/vo/EApproval.java
  GroupwarePro/src/main/resources/mappers/eApproval-mapper.xml
  GroupwarePro/src/main/resources/mybatis-config.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eAEnrollForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eAMain.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eApprDetailView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eCommonForm.jsp
Labels: UI 구현, 기능 구현

#162 채팅 파트 누락 기능 구현
  GroupwarePro/src/main/java/com/kh/spring/chat/controller/ChatController.java
  GroupwarePro/src/main/java/com/kh/spring/member/controller/MemberController.java
  GroupwarePro/src/main/webapp/WEB-INF/views/chat/app-chat.jsp
Labels: 기능 구현

#164 알림 팝업 UI수정, 메인창에서만 뜨도록 함
  GroupwarePro/src/main/webapp/WEB-INF/views/common/header.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/main.jsp
Labels: 기능 구현

#166 알림 팝업 수정 - 메인페이지 구별 조건 로직 추가
  GroupwarePro/src/main/java/com/kh/spring/member/controller/MemberController.java
  GroupwarePro/src/main/webapp/WEB-INF/views/chat/app-chat.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/common/header.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/main.jsp
Labels: 기능 구현

#170 전자결재 사이드바 분리
  GroupwarePro/src/main/java/com/kh/spring/eApproval/controller/EApprovalController.java
  GroupwarePro/src/main/resources/mappers/eApproval-mapper.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/approveDocumentsView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/draftDocumentsView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eAEnrollForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eAMain.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eASidebar.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eApprDetailView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eCommonForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eFormsView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/waitDocumentsView.jsp
Labels: 기능 구현

#172 [전사 공지사항,월간 식단표][기능][구현진행]
  GroupwarePro/pom.xml
  GroupwarePro/src/main/java/com/kh/spring/notice/controller/NoticeController.java
  GroupwarePro/src/main/java/com/kh/spring/notice/model/service/NoticeServiceImpl.java
  GroupwarePro/src/main/java/com/kh/spring/tblMeals/controller/TblMealsController.java
  GroupwarePro/src/main/java/com/kh/spring/tblMeals/model/dao/TblMealsDao.java
  GroupwarePro/src/main/java/com/kh/spring/tblMeals/model/service/TblMealsService.java
  GroupwarePro/src/main/java/com/kh/spring/tblMeals/model/service/TblMealsServiceImpl.java
  GroupwarePro/src/main/java/com/kh/spring/tblMeals/model/vo/TblMealsCal.java
  GroupwarePro/src/main/resources/mappers/tblMeals-mapper.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/notice/noticeEnrollForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/notice/noticeListView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/tblMeals/tbl_meals.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/tblMeals/tmRegisterForm.jsp
  GroupwarePro/src/main/webapp/resources/fullcalendar/main.css
  GroupwarePro/src/main/webapp/resources/upload_files/20211120135112.xlsx
  GroupwarePro/src/main/webapp/resources/upload_files/20211120160208.xlsx
  GroupwarePro/src/main/webapp/resources/upload_files/20211120161650.xlsx
Labels: 기능 구현

#175 근태관리 UI수정
  GroupwarePro/src/main/java/com/kh/spring/hr/controller/HrController.java
  GroupwarePro/src/main/java/com/kh/spring/hr/model/dao/HrDao.java
  GroupwarePro/src/main/java/com/kh/spring/hr/model/service/HrService.java
  GroupwarePro/src/main/java/com/kh/spring/hr/model/service/HrServiceImpl.java
  GroupwarePro/src/main/java/com/kh/spring/hr/model/vo/Work.java
  GroupwarePro/src/main/resources/mappers/hr-mapper.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/hr/hrMain.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/main.jsp
Labels: 기능 구현

#177 일정/예약 파트 코드 정리
  GroupwarePro/src/main/webapp/resources/dist/js/pages/main/components/Reservation.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/App.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/components/Reservation.js
Labels: 마무리 정리

#179 메인화면 출퇴근버튼 추가
  GroupwarePro/src/main/java/com/kh/spring/eApproval/controller/EApprovalController.java
  GroupwarePro/src/main/java/com/kh/spring/eApproval/model/dao/EApprovalDao.java
  GroupwarePro/src/main/java/com/kh/spring/eApproval/model/service/EApprovalService.java
  GroupwarePro/src/main/java/com/kh/spring/eApproval/model/service/EApprovalServiceImpl.java
  GroupwarePro/src/main/java/com/kh/spring/eApproval/model/vo/EApproval.java
  GroupwarePro/src/main/java/com/kh/spring/eApproval/model/vo/EForm.java
  GroupwarePro/src/main/java/com/kh/spring/hr/controller/HrController.java
  GroupwarePro/src/main/java/com/kh/spring/member/controller/MemberController.java
  GroupwarePro/src/main/resources/mappers/eApproval-mapper.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/approveDocumentsView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/draftDocumentsView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eAEnrollForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eAMain.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eASidebar.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eApprDetailView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/eApproval/eCommonForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/hr/hrMain.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/hr/hrSidebar.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/main.jsp
  GroupwarePro/src/main/webapp/resources/upload_files/20211128052503.png
  GroupwarePro/src/main/webapp/resources/upload_files/20211128052540.png
  GroupwarePro/src/main/webapp/resources/upload_files/20211128052837.docx
  GroupwarePro/src/main/webapp/resources/upload_files/20211128063250.docx
  GroupwarePro/src/main/webapp/resources/upload_files/20211128063506.docx
  GroupwarePro/src/main/webapp/resources/upload_files/20211128063606.docx
Labels: 기능 구현

#181 survey 최신
  GroupwarePro/src/main/java/com/kh/spring/survey/controller/SurveyController.java
  GroupwarePro/src/main/java/com/kh/spring/survey/model/dao/SurveyDao.java
  GroupwarePro/src/main/java/com/kh/spring/survey/model/service/SurveyService.java
  GroupwarePro/src/main/java/com/kh/spring/survey/model/service/SurveyServiceImpl.java
  GroupwarePro/src/main/java/com/kh/spring/survey/model/vo/Essay.java
  GroupwarePro/src/main/resources/mappers/essay-mapper.xml
  GroupwarePro/src/main/resources/mappers/survey-mapper.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/manager/managerMemberList.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/popupNotice/popupNoticeList.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/survey/surveyQuestionForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/survey/surveyQuestionInsertForm.jsp
Labels: 기능 구현

#182 일정 예약 테스트 중 발견된 오류 수정
  GroupwarePro/src/main/webapp/resources/dist/js/pages/calendar/App.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/calendar/components/sidemenu/SideMenuEdit.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/App.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/components/sidemenu/SideMenuEdit.js
Labels: 기능 구현

#184 일정 예약 코드 정리
  GroupwarePro/src/main/webapp/resources/dist/js/pages/calendar/App.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/calendar/components/Calendar.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/calendar/components/SideMenu.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/calendar/components/sidemenu/SideMenuCal.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/calendar/components/sidemenu/SideMenuEdit.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/calendar/components/sidemenu/daterangepicker/DateRangePicker.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/main/App.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/main/components/Calendar.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/main/components/Reservation.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/App.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/components/Reservation.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/components/SideMenu.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/components/reservation/ReservationDetail.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/components/sidemenu/SideMenuAsset.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/components/sidemenu/SideMenuCategory.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/components/sidemenu/SideMenuEdit.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/components/sidemenu/SideMenuList.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/components/sidemenu/daterangepicker/DateRangePicker.js
  GroupwarePro/src/main/webapp/resources/dist/js/pages/reservation/core/Router.js
Labels: 마무리 정리

#186 [전사공지사항,식단관리표][기능,UI],[구현진행]
  GroupwarePro/src/main/java/com/kh/spring/notice/controller/NoticeController.java
  GroupwarePro/src/main/java/com/kh/spring/notice/model/dao/NoticeDao.java
  GroupwarePro/src/main/java/com/kh/spring/notice/model/service/NoticeService.java
  GroupwarePro/src/main/java/com/kh/spring/notice/model/service/NoticeServiceImpl.java
  GroupwarePro/src/main/java/com/kh/spring/notice/model/vo/CompanyNotice.java
  GroupwarePro/src/main/java/com/kh/spring/tblMeals/controller/TblMealsController.java
  GroupwarePro/src/main/java/com/kh/spring/tblMeals/model/dao/TblMealsDao.java
  GroupwarePro/src/main/java/com/kh/spring/tblMeals/model/service/TblMealsService.java
  GroupwarePro/src/main/java/com/kh/spring/tblMeals/model/service/TblMealsServiceImpl.java
  GroupwarePro/src/main/resources/mappers/notice-mapper.xml
  GroupwarePro/src/main/resources/mappers/tblMeals-mapper.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/notice/noticeDetailView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/notice/noticeEnrollForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/notice/noticeListView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/notice/noticeUpdateForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/tblMeals/tbl_meals.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/tblMeals/tmRegisterForm.jsp
  GroupwarePro/src/main/webapp/resources/upload_files/20211122232615.txt
  GroupwarePro/src/main/webapp/resources/upload_files/20211122234905.txt
  GroupwarePro/src/main/webapp/resources/upload_files/20211123020724.txt
  GroupwarePro/src/main/webapp/resources/upload_files/20211124001237.txt
  GroupwarePro/src/main/webapp/resources/upload_files/20211128184522.txt
Labels: UI 구현, 기능 구현

#187 설문 작성 , 답변 작성
  GroupwarePro/src/main/java/com/kh/spring/manager/controller/ManagerController.java
  GroupwarePro/src/main/java/com/kh/spring/member/controller/MemberController.java
  GroupwarePro/src/main/java/com/kh/spring/survey/controller/SurveyController.java
  GroupwarePro/src/main/java/com/kh/spring/survey/model/dao/SurveyDao.java
  GroupwarePro/src/main/java/com/kh/spring/survey/model/service/SurveyService.java
  GroupwarePro/src/main/java/com/kh/spring/survey/model/service/SurveyServiceImpl.java
  GroupwarePro/src/main/java/com/kh/spring/survey/model/vo/EssayAnswer.java
  GroupwarePro/src/main/resources/mappers/member-mapper.xml
  GroupwarePro/src/main/resources/mappers/survey-mapper.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/common/m_header.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/common/m_sidebar.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/member/memberEnrollForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/member/memberFindForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/popupNotice/popupNoticeInsertForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/popupNotice/popupNoticeUpdateForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/survey/surveyAnswerForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/survey/surveyInsertForm.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/survey/surveyQuestionForm.jsp
Labels: 기능 구현

#189 메인 페이지 프로필 사진 직급에 따라 변경하도록 구현
  GroupwarePro/src/main/resources/mappers/member-mapper.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/main.jsp
  GroupwarePro/src/main/webapp/resources/assets/images/adminImg.png
  GroupwarePro/src/main/webapp/resources/assets/images/profile1.png
  GroupwarePro/src/main/webapp/resources/assets/images/profile2.png
  GroupwarePro/src/main/webapp/resources/assets/images/profile3.png
Labels: 마무리 정리

#191 근태관리 월 이동기능 수정
  GroupwarePro/src/main/java/com/kh/spring/hr/controller/HrController.java
  GroupwarePro/src/main/java/com/kh/spring/hr/model/dao/HrDao.java
  GroupwarePro/src/main/java/com/kh/spring/hr/model/service/HrService.java
  GroupwarePro/src/main/java/com/kh/spring/hr/model/service/HrServiceImpl.java
  GroupwarePro/src/main/java/com/kh/spring/hr/model/vo/Work.java
  GroupwarePro/src/main/java/com/kh/spring/hr/model/vo/WorkSInfo.java
  GroupwarePro/src/main/resources/mappers/hr-mapper.xml
  GroupwarePro/src/main/webapp/WEB-INF/views/hr/workListView.jsp
  GroupwarePro/src/main/webapp/WEB-INF/views/main.jsp
Labels: 기능 구현
